### ISSUE TITLE
Thanks !

### ISSUE THREAD

**Issue by drupol** [WyriHaximus/github-action-composer-php-versions-in-range#11]
Thank you so much for this brilliant idea, I'm going to use this all the time now ! (first time in here: https://github.com/loophp/collection/actions/runs/2857169055)

To be honest, I had this idea a couple of months ago when working on [loophp/nix-shell](https://github.com/loophp/nix-shell/), then for some reason got caught doing something else.

Keep up the good work !

**Comment by WyriHaximus** [comment]
Thanks, glad to hear that! Started working on this because I got tired of updating my workflows every time a new PHP version came out, and by adding the upcoming PHP version in there you can free testing of un release new major/minor PHP versions early on.
